[[constraint]]
  name = "github.com/anthonynsimon/bild"
  version = "0.10.0"

[[constraint]]
  name = "github.com/matryer/is"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
